### ISSUE TITLE
Parsing website TOC fails due to URL 301

### ISSUE THREAD

**Issue by tprynn** [chintogtokh/worm-to-ebook#1]
The url http://parahumans.wordpress.com/category/stories-arcs-1-10/arc-4-shell/4-x-interlude/ leads to a 301 redirect, which curl does not follow by default.

Temporary fix: On line 21, change the url to a non-301 url such as https://parahumans.wordpress.com/category/stories-arcs-1-10/arc-1-gestation/1-01/

A permanent fix would be to add '-L' flag to curl, so it follows http redirects.

Thanks for the simple tool, it saved me a lot of time!

**Comment by tprynn** [comment]
Also, line 34 will fail if the url is https, so that needs to be fixed as well.

The underlying issue is that parahumans.wordpress.com now redirects to https by default.

**Comment by chintogtokh** [comment]
Thanks, fixed (I think). Also, it works for Pact without issues, it seems.
